spring:
    application:
        name: web-client

server:
    port: 9000
    servlet:
        context-path: /
management:
    server:
        port: 9000
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: "*"


eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        instance-id: ${spring.application.name}:${server.port}
