version: '3.5'
x-common-settings: &common-settings
  restart: on-failure
  environment:
    - SPRING_PROFILES_ACTIVE=docker

services:
  discovery-server:
    build: discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    <<: *common-settings

  api-gateway:
    depends_on:
      - discovery-server
    build: api-gateway/
    container_name: api-gateway
    ports:
      - "80:80"
    <<: *common-settings


  product-service:
    container_name: product-service
    depends_on:
      - discovery-server
    build: product-service/
    <<: *common-settings

  web-client:
    container_name: web-client
    depends_on:
      - product-service
    build: web-client/
    ports:
      - "9000:9000"
    <<: *common-settings

  feign-client:
    container_name: feign-client
    depends_on:
      - product-service
    build: feign-client/
    ports:
      - "8000:8000"
    <<: *common-settings


