
app:
    eureka-server: localhost

eureka:
    client:
        serviceUrl:
            defaultZone: http://${app.eureka-server}:${eureka.client.serviceUrl.port}/eureka/
            port: 8761
    instance:
        instance-id: ${spring.application.name}-${random.int(1000)}
server:
    port: 80
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: product_service
                  uri: lb://product-service
                  predicates:
                      - Path=/api/products/**
