info:
  app:
  name: API Gateway
  description: API Gateway
  version: 1.0.0

server:
    port: 9090
    servlet:
      context-path: /
management:
  server:
    port: 9090
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: product_service
                  uri: lb://product-service
                  predicates:
                      - Path=/api/products/**
                - id: web-client
                  uri: lb://web-client
                  predicates:
                      - Path=/web/**
                - id: feign-client
                  uri: lb://feign-client
                  predicates:
                      - Path=/feign/**

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
      instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: INFO