spring:
    application:
        name: discovery-server

info:
    app:
    name: Discovery Server
    description: Discovery Server
    version: 1.0.0

server:
    port: 8761
    servlet:
        context-path: /
management:
    server:
        port: 8761
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: "*"

eureka:
    instance:
        hostname: localhost
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
