spring:
    application:
        name: product-service
server:
    port: 0


info:
    app:
    name: Product Service
    description: Product Service
    version: 1.0.0



eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        instance-id: ${spring.application.name}:${random.int(1000)}