spring:
    application:
        name: product-service
server:
    port: 0


app:
    eureka-server: localhost

eureka:
    client:
        serviceUrl:
            defaultZone: http://{app.eureka-server}:8761/eureka/
    instance:
        instance-id: ${spring.application.name}:${random.int(1000)}